/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const InternshipInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'category' : IDL.Text,
  'location' : IDL.Text,
  'applicationLink' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CompanySubmission = IDL.Record({
  'id' : IDL.Nat,
  'additionalComments' : IDL.Text,
  'contactPerson' : IDL.Text,
  'submittedAt' : IDL.Int,
  'submittedBy' : IDL.Principal,
  'email' : IDL.Text,
  'companyName' : IDL.Text,
  'partnershipInterest' : IDL.Bool,
  'legalDocuments' : IDL.Vec(ExternalBlob),
  'internshipDetails' : IDL.Text,
});
export const ContactFormSubmission = IDL.Record({
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const AccountType = IDL.Variant({
  'company' : IDL.Null,
  'student' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'accountType' : AccountType,
});
export const CategoryCount = IDL.Record({
  'count' : IDL.Nat,
  'category' : IDL.Text,
});
export const Internship = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'category' : IDL.Text,
  'location' : IDL.Text,
  'applicationLink' : IDL.Text,
});
export const CompanySubmissionInput = IDL.Record({
  'additionalComments' : IDL.Text,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'companyName' : IDL.Text,
  'partnershipInterest' : IDL.Bool,
  'legalDocuments' : IDL.Vec(ExternalBlob),
  'internshipDetails' : IDL.Text,
});
export const ContactFormInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInternship' : IDL.Func([InternshipInput], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteInternship' : IDL.Func([IDL.Nat], [], []),
  'getAllCompanySubmissions' : IDL.Func(
      [],
      [IDL.Vec(CompanySubmission)],
      ['query'],
    ),
  'getAllContactFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryCounts' : IDL.Func([], [IDL.Vec(CategoryCount)], ['query']),
  'getInternship' : IDL.Func([IDL.Nat], [IDL.Opt(Internship)], ['query']),
  'getInternships' : IDL.Func([], [IDL.Vec(Internship)], ['query']),
  'getInternshipsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Internship)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'promoteAdminUsers' : IDL.Func([], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitCompanySurvey' : IDL.Func([CompanySubmissionInput], [IDL.Nat], []),
  'submitContactForm' : IDL.Func([ContactFormInput], [], []),
  'updateInternship' : IDL.Func([IDL.Nat, InternshipInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const InternshipInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'category' : IDL.Text,
    'location' : IDL.Text,
    'applicationLink' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CompanySubmission = IDL.Record({
    'id' : IDL.Nat,
    'additionalComments' : IDL.Text,
    'contactPerson' : IDL.Text,
    'submittedAt' : IDL.Int,
    'submittedBy' : IDL.Principal,
    'email' : IDL.Text,
    'companyName' : IDL.Text,
    'partnershipInterest' : IDL.Bool,
    'legalDocuments' : IDL.Vec(ExternalBlob),
    'internshipDetails' : IDL.Text,
  });
  const ContactFormSubmission = IDL.Record({
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const AccountType = IDL.Variant({
    'company' : IDL.Null,
    'student' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'accountType' : AccountType,
  });
  const CategoryCount = IDL.Record({
    'count' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Internship = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'category' : IDL.Text,
    'location' : IDL.Text,
    'applicationLink' : IDL.Text,
  });
  const CompanySubmissionInput = IDL.Record({
    'additionalComments' : IDL.Text,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'companyName' : IDL.Text,
    'partnershipInterest' : IDL.Bool,
    'legalDocuments' : IDL.Vec(ExternalBlob),
    'internshipDetails' : IDL.Text,
  });
  const ContactFormInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInternship' : IDL.Func([InternshipInput], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteInternship' : IDL.Func([IDL.Nat], [], []),
    'getAllCompanySubmissions' : IDL.Func(
        [],
        [IDL.Vec(CompanySubmission)],
        ['query'],
      ),
    'getAllContactFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryCounts' : IDL.Func([], [IDL.Vec(CategoryCount)], ['query']),
    'getInternship' : IDL.Func([IDL.Nat], [IDL.Opt(Internship)], ['query']),
    'getInternships' : IDL.Func([], [IDL.Vec(Internship)], ['query']),
    'getInternshipsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Internship)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'promoteAdminUsers' : IDL.Func([], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitCompanySurvey' : IDL.Func([CompanySubmissionInput], [IDL.Nat], []),
    'submitContactForm' : IDL.Func([ContactFormInput], [], []),
    'updateInternship' : IDL.Func([IDL.Nat, InternshipInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };