/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountType = { 'company' : null } |
  { 'student' : null };
export interface CategoryCount { 'count' : bigint, 'category' : string }
export interface CompanySubmission {
  'id' : bigint,
  'additionalComments' : string,
  'contactPerson' : string,
  'submittedAt' : bigint,
  'submittedBy' : Principal,
  'email' : string,
  'companyName' : string,
  'partnershipInterest' : boolean,
  'legalDocuments' : Array<ExternalBlob>,
  'internshipDetails' : string,
}
export interface CompanySubmissionInput {
  'additionalComments' : string,
  'contactPerson' : string,
  'email' : string,
  'companyName' : string,
  'partnershipInterest' : boolean,
  'legalDocuments' : Array<ExternalBlob>,
  'internshipDetails' : string,
}
export interface ContactFormInput {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface ContactFormSubmission {
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
}
export type ExternalBlob = Uint8Array;
export interface Internship {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'company' : string,
  'category' : string,
  'location' : string,
  'applicationLink' : string,
}
export interface InternshipInput {
  'title' : string,
  'description' : string,
  'company' : string,
  'category' : string,
  'location' : string,
  'applicationLink' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'accountType' : AccountType,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInternship' : ActorMethod<[InternshipInput], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteInternship' : ActorMethod<[bigint], undefined>,
  'getAllCompanySubmissions' : ActorMethod<[], Array<CompanySubmission>>,
  'getAllContactFormSubmissions' : ActorMethod<
    [],
    Array<ContactFormSubmission>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryCounts' : ActorMethod<[], Array<CategoryCount>>,
  'getInternship' : ActorMethod<[bigint], [] | [Internship]>,
  'getInternships' : ActorMethod<[], Array<Internship>>,
  'getInternshipsByCategory' : ActorMethod<[string], Array<Internship>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'promoteAdminUsers' : ActorMethod<[], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCompanySurvey' : ActorMethod<[CompanySubmissionInput], bigint>,
  'submitContactForm' : ActorMethod<[ContactFormInput], undefined>,
  'updateInternship' : ActorMethod<[bigint, InternshipInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];